version: '3'
volumes:
  prisma_data:
  data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13541:13541"
    volumes:
      - prisma_data:/app/prisma/data
      - data:/app/data
